In [ ]:
import pandas as pd

In [5]:
# Load the Icelandic age distribution data
icelandic_age_distribution = pd.read_csv('icelandic_age_distribution.csv')

# Define a dictionary for min and max age limits
define_age_limits = {
    "0-4 years": (0, 4),
    "5-9 years": (5, 9),
    "10-14 years": (10, 14),
    "15-19 years": (15, 19),
    "20-24 years": (20, 24),
    "25-29 years": (25, 29),
    "30-34 years": (30, 34),
    "35-39 years": (35, 39),
    "40-44 years": (40, 44),
    "45-49 years": (45, 49),
    "50-54 years": (50, 54),
    "55-59 years": (55, 59),
    "60-64 years": (60, 64),
    "65-69 years": (65, 69),
    "70-74 years": (70, 74),
    "75-79 years": (75, 79),
    "80-84 years": (80, 84),
    "85-89 years": (85, 89),
    "90-94 years": (90, 94),
    "95 years and older": (95, 100)
}

# Map the dictionary to create two new columns: Min Age and Max Age
icelandic_age_distribution['Min Age'] = icelandic_age_distribution['Age groups'].map(
    lambda x: define_age_limits[x][0])
icelandic_age_distribution['Max Age'] = icelandic_age_distribution['Age groups'].map(
    lambda x: define_age_limits[x][1])

# Save the processed DataFrame
icelandic_age_distribution_postprocessed = icelandic_age_distribution

# Optionally, save to a new CSV file
icelandic_age_distribution_postprocessed.to_csv(
    'icelandic_age_distribution_postprocessed.csv', index=False)

# Display the first few rows of the processed DataFrame
icelandic_age_distribution_postprocessed.head()

           Age groups  Males  Females  Min Age  Max Age
0  95 years and older   0.04     0.10       95      100
1         90-94 years   0.20     0.32       90       94
2         85-89 years   0.46     0.60       85       89
3         80-84 years   0.86     1.00       80       84
4         75-79 years   1.49     1.55       75       79